export const SEARCH_BY_NAME = `SEARCH_BY_NAME`;
export const SEARCH_BY_DATE = `SEARCH_BY_DATE`;
export const FETCH_START = `FETCH_START`;
export const FETCH_FAIL = `FETCH_FAIL`;
export const FETCH_COMPLETE = `FETCH_COMPLETE`;
export const FETCH_FILTER_COMPLETE = `FETCH_FILTER_COMPLETE`;
export const CLEAR_NAME_FILTER = `CLEAR_NAME_FILTER`;
